In [1]:
import pandas as pd
import numpy as np
headers = ['Sale','SalesAmountInEuro','time_delay_for_conversion','click_timestamp','nb_clicks_1week','product_price' ,'product_age_group' ,'device_type','audience_id' ,'product_gender' ,'product_brand' ,'product_category(1)', 'product_category(2)', 'product_category(3)', 'product_category(4)', 'product_category(5)', 'product_category(6)', 'product_category(7)', 'product_country', 'product_id' ,'product_title' ,'partner_id' ,'user_id']
df_original = pd.read_csv('D:\Projekty\Engineering_Thesis\Dataset\Criteo_Conversion_Search\CriteoSearchData-sorted.csv',
                 sep='\t',
                 nrows=1000001,
                 names=headers,
                 low_memory=False,
                 usecols=[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22])
# df_original = df_original.sort(column='click_timestamp', ascending=True)
# df_original.iloc[:10,:]
df_original = df_original.drop(df_original.index[0])
lst = [df_original]

In [2]:
df_original[:5]

,Sale,SalesAmountInEuro,time_delay_for_conversion,click_timestamp,nb_clicks_1week,product_price,product_age_group,device_type,audience_id,product_gender,...,product_category(3),product_category(4),product_category(5),product_category(6),product_category(7),product_country,product_id,product_title,partner_id,user_id
1,0,-1.0,-1,1596439471,0,0.0,4C90FD52FC53D2C1C205844CB69575AB,D7D1FB49049702BF6338894757E0D959,865A11AEC419E0B83637E01693CA6534,A5D15FC386510762EC0DDFF54ABE6F94,...,925C269ABCB1ABD1B1404E9AF9BAC32C,-1,-1,-1,-1,2AC62132FBCFA093B9426894A4BC6278,E0B8A58942AD00411F94DC480E187E64,79FB52BC086F410AFFD19B69426DF923 7FE78A2301139...,DE8AF4DB950D7A4F844B744FA402C4A8,95C3CF40CFEFD9DEF99995CD90A23D42
2,0,-1.0,-1,1596439471,320,0.0,-1,7E56C27BFF0305E788DA55A029EC4988,-1,-1,...,0279CBF3081FFB710CE52B9E0BA4AABF,35A13FB2AB63E920B7D71C5957131606,-1,-1,-1,989EEF92F2A525DD896557425EA7C4C7,F29147A240F4B1945EBAC85159AB9A56,7490FDD3B232D01748AB294BCA9854D0 25887A6625AAD...,6BFFDE668C5BC3938C875D3D0940E699,73F7922D0081EE864EABA4EFED7817EF
3,1,21.24097,965274,1596439471,0,24.99,4C90FD52FC53D2C1C205844CB69575AB,D7D1FB49049702BF6338894757E0D959,-1,1B491180398E2F0390E6A588B3BCE291,...,-1,-1,-1,-1,-1,2AC62132FBCFA093B9426894A4BC6278,F73208C88398FDA9BD1522A4CA67F8B8,BA2580C036E251F1A4651A1DF94C7E3A 949A59B278D8B...,925829CF82DFDC74DE3F88F003CE7BEF,A546410581F20DC088ED664C6513ACB7
4,0,-1.0,-1,1596439472,428,0.0,4C90FD52FC53D2C1C205844CB69575AB,D7D1FB49049702BF6338894757E0D959,8087F618427981D8E4086F0CC657CA99,1B491180398E2F0390E6A588B3BCE291,...,FAE775DB79B7E40FB3E581B2755783A4,-1,-1,-1,-1,989EEF92F2A525DD896557425EA7C4C7,C0FD3010A8E54E0DA78EBE451FF28128,0AD77EF609C0582FBF99A1B6AC3E87A6 F6F4CBF56EBB5...,C38B671959ACFDA46C5129405124203E,34A21E0D4EA7F2AC06F9B7310BDAC770
5,0,-1.0,-1,1596439472,1,0.0,4C90FD52FC53D2C1C205844CB69575AB,D7D1FB49049702BF6338894757E0D959,4C8453541EC315B401CE392F1B259D11,A5D15FC386510762EC0DDFF54ABE6F94,...,0365AD68DB988045830FA1D8F8A7DB3A,-1,-1,-1,-1,989EEF92F2A525DD896557425EA7C4C7,6C3E65D832A071BC1DBC3DBDC4E6EB06,90901AF186076CF02A33D5A92CC7097D 5BB81871A6C63...,51EBAAC05E372CBCDF0F207517A225AB,FDC2E3772FF4DDD8C380D904AE97736D

In [3]:
print(df_original.isnull().sum())
df = df_original.dropna(axis=0) # usuwanie wierszy, ktÃ³re zawierajÄ… null
df.isnull().sum()

Sale                            0
SalesAmountInEuro               0
time_delay_for_conversion       0
click_timestamp                 0
nb_clicks_1week                 0
product_price                   0
product_age_group               0
device_type                     0
audience_id                     0
product_gender                  0
product_brand                   0
product_category(1)             0
product_category(2)             0
product_category(3)             0
product_category(4)             0
product_category(5)             0
product_category(6)             0
product_category(7)             0
product_country                 0
product_id                      0
product_title                2467
partner_id                      0
user_id                         0
dtype: int64

Sale                         0
SalesAmountInEuro            0
time_delay_for_conversion    0
click_timestamp              0
nb_clicks_1week              0
product_price                0
product_age_group            0
device_type                  0
audience_id                  0
product_gender               0
product_brand                0
product_category(1)          0
product_category(2)          0
product_category(3)          0
product_category(4)          0
product_category(5)          0
product_category(6)          0
product_category(7)          0
product_country              0
product_id                   0
product_title                0
partner_id                   0
user_id                      0
dtype: int64

In [4]:
columns = list(df)
for id, name in enumerate(columns):
    count = len(df.iloc[:,id].unique())
    print(str(id) + "\t" + str(count) +  "\t" + name  )

0	2	Sale
1	51695	SalesAmountInEuro
2	59290	time_delay_for_conversion
3	424739	click_timestamp
4	1824	nb_clicks_1week
5	13788	product_price
6	9	product_age_group
7	5	device_type
8	6345	audience_id
9	14	product_gender
10	11428	product_brand
11	22	product_category(1)
12	161	product_category(2)
13	877	product_category(3)
14	1227	product_category(4)
15	630	product_category(5)
16	142	product_category(6)
17	3	product_category(7)
18	17	product_country
19	232124	product_id
20	125389	product_title
21	199	partner_id
22	924093	user_id

In [5]:
# index_of_columns_with_lower_than_1000_unique_values = []
# excluded_indexes = [0, 1, 2, 3, 4, 5]
# for id, count in enumerate(count_of_unique_values_in_each_row):
#     if id not in excluded_indexes:
#         if count < 1000:
#             index_of_columns_with_lower_than_1000_unique_values.append(id)
# df = pd.get_dummies(df.iloc[:,index_of_columns_with_lower_than_1000_unique_values])

# df = pd.get_dummies(df.iloc[:,[6,7,9,11,12,13,14,15,16,17,18,21]])

import time
start = time.time()
df_copy=df
index_of_columns_to_change_to_one_hot_vectors = [6, 7, 9, 11, 12, 13, 14, 15, 16, 17, 18, 21]

df_only_one_hot_vectors_columns = pd.get_dummies(df_copy.iloc[:,index_of_columns_to_change_to_one_hot_vectors])
df_common_columns = df.iloc[:,[0, 1, 2, 4, 5 ]]


df_copy = pd.concat([df_common_columns, df_only_one_hot_vectors_columns ], axis=1, sort=True)

df_copy[:5]

end = time.time()
print(end - start)

TypeError: unsupported operand type(s) for -: 'float' and 'module'

In [7]:
start = time.time()
df_copy.to_csv("one_hot_vectors_data_1mln.csv", sep='\t', index=False)
end = time.time()
print(end - start)

TypeError: unsupported operand type(s) for -: 'float' and 'module'