In [209]:
import pandas as pd
import numpy as np
headers = ['Sale','SalesAmountInEuro','time_delay_for_conversion','click_timestamp','nb_clicks_1week','product_price' ,'product_age_group' ,'device_type','audience_id' ,'product_gender' ,'product_brand' ,'product_category(1)', 'product_category(2)', 'product_category(3)', 'product_category(4)', 'product_category(5)', 'product_category(6)', 'product_category(7)', 'product_country', 'product_id' ,'product_title' ,'partner_id' ,'user_id']
df_original = pd.read_csv('D:\Projekty\Engineering_Thesis\Dataset\Criteo_Conversion_Search\CriteoSearchData-sorted.csv',
                 sep='\t',
                 nrows=10000,
                 names=headers,
                 low_memory=False,
                 usecols=[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22])
# df_original = df_original.sort(column='click_timestamp', ascending=True)
# df_original.iloc[:10,:]
df_original = df_original.drop(df_original.index[0])
lst = [df_original]

In [210]:
df_original[:5].to_dict()['Sale'][3]

'1'

In [211]:
def read_requred_column_names():
    required_column_name_file = open('required_column_names_list.txt', 'r') 
    required_column_names_list = required_column_name_file.read().splitlines()
    return required_column_names_list

In [212]:
# tworzenie dataframeu ze ze wszystkimi wymaganymi kolumnami (unikalnymi wartościami kolumn z poprzedniego poodpunktu)
name_of_required_columns_list = read_requred_column_names()
df_transformed = pd.DataFrame(columns=name_of_required_columns_list)
df_transformed

Empty DataFrame
Columns: [Sale, SalesAmountInEuro, time_delay_for_conversion, click_timestamp, nb_clicks_1week, product_age_group_4C90FD52FC53D2C1C205844CB69575AB, product_age_group_-1, product_age_group_88460293E9517D21E39AA889BD5AADC8, product_age_group_0CD76C7030D0900BE250C8D41703D180, product_age_group_538912C31E773613AB51FBAE58492476, product_age_group_921B36149E5B081FD24450BFE2CE4430, product_age_group_E7BD5A29457B8E92582951B586319A9C, product_age_group_D72D7E92251E4C54C786FDEFFA4DEF5A, product_age_group_3FEC071EF6B3D061D8804E0522FF4D2A, product_age_group_F716A9DB9D084CD5CFBDA30A923016E1, product_age_group_09FE9D03FC0E0079F8C7ED4EB40B8AC1, product_age_group_A443B40A19DB45968C2825CE225368DF, device_type_D7D1FB49049702BF6338894757E0D959, device_type_7E56C27BFF0305E788DA55A029EC4988, device_type_FF2C446555E3822B0E0FC3406116E86D, device_type_-1, device_type_B432A885981287B47E08B41E802860B2, device_type_0C297EB7365042A7DCB803298164359F, device_type_C1ED32BB62670069B0ACE459169A7EAA, device_type_1D2373C2A02F5A307C1F0C697ECF8429, device_type_D5AF1EAB7526F8539A66F715079AB628, product_gender_A5D15FC386510762EC0DDFF54ABE6F94, product_gender_-1, product_gender_1B491180398E2F0390E6A588B3BCE291, product_gender_C45A9AC6D102ACAEEDF0D6F78636D84A, product_gender_28F311FA00BD3B4D076659D87EE3AE8D, product_gender_D7B42B0C4D807EF1C13F79948743E9DA, product_gender_6EFABCEDA36A931DBF760F88970BAF0E, product_gender_D894202FD3ABAE0B55F9FAE133412DE5, product_gender_26FE89E9DD2E6FC18AA5BE1F6D5A6870, product_gender_0FB06F1EAC1E00A436B336C5DF3C14AF, product_gender_86E2AFBF909EC95B069893FF0BBC5B26, product_gender_C83584C67375245584CEBF5DCE5BEE2D, product_gender_4E0E101FFE4550D92B5CCDEF67A1FE17, product_gender_3B3F1EFC68D245B766D311E45CD6B955, product_gender_36CA8D7C5D7CDDBA095271FA7154EC5F, product_gender_350E4EE263AE2ED2AC0811046F2519C8, product_gender_2FCCC43F6E5A738D7A763E28DCBE235B, product_gender_8CE4C5DDEE22BB8EE50CF418ED81591C, product_category(1)_7F286560861764CCB93C90B7AA833949, product_category(1)_033E492229C2222EFAA16EE8A6462D8B, product_category(1)_7532B3FBAFEC164460C4ED6FEB0C022C, product_category(1)_944B2A351FEFAC79AEAA9DA57E1B351F, product_category(1)_62D6A49514020FA0B2E434DB0B506005, product_category(1)_9D307E5B713DE5E90D787BE9F802AFBB, product_category(1)_-1, product_category(1)_EC997D43AC86A75D9B88A1051F86A67C, product_category(1)_635623BABBB7DA2E072D8C339F606E15, product_category(1)_88CED8BA3AA711A20ACF8B1FC574F218, product_category(1)_2551A1FA7839742971CDF4C67667E17A, product_category(1)_13C26D10258053889D75D9B9CA922EC7, product_category(1)_B4B45C6CE5FC4DE45AB02974D8849DBD, product_category(1)_2134F56D3769B5022DB7172F1536B749, product_category(1)_E02400CDAD96905D88E932FE9B7D3552, product_category(1)_111C91D6B0D89C84BF196FED8DBE7BBB, product_category(1)_5D656311CF9F47E34248BE9FBFF194A0, product_category(1)_DDC2B3CC38945E431DE1B3F59EC56680, product_category(1)_B83EF4115DC165749F3FCB737CC1044D, product_category(1)_6A21F69EBA80612A04B0F6BAC857AAF2, product_category(1)_69995F9BE9CA542AF2D7A3A2344C2B0A, product_category(1)_5693606EF31931A11D5985E046ABBE75, product_category(2)_1F7C0436C367A14B4C62294F235D45A4, product_category(2)_891EE660A73D9A6E1F4BD6149E613C44, product_category(2)_CD599E5A946D00A81A875E085F7EF1E8, product_category(2)_77FFC91A6157E50A0A114135F18BB1DB, product_category(2)_093C266CF22FC590758F27FD8B32CCBA, product_category(2)_26DF34C9B5E43303C2D298D28339FE09, product_category(2)_8C0191D426F4A3944D1E8BC2E012646D, product_category(2)_5DA3309EAFC202FA6674E96D1A956E42, product_category(2)_-1, product_category(2)_50FF54E71F635597F839D2428054DC0C, product_category(2)_9868E1576979CBF21E2B80E1623F67B9, product_category(2)_1CA629F8F10B2541E08A1A994CDA0F1D, product_category(2)_80DF9DD23FCDB4F869BD699276D0A677, product_category(2)_59DF0A0F3F9417025D07FE50A4E762AC, product_category(2)_B38982D91795B014244C088FFF1B7C88, product_category(2)_BAF3B3C341EAE48387D11D673237916B, product_category(2)_FE4A86571601A1EF619CDB48BCD7F9A3, product_category(2)_65838FD696D6EEF1348247F87B8A298E, product_category(2)_D8C555B86D5912C47B979FD96E6D802D, product_category(2)_41DF6386116137A19E7DBC07CE44C95A, product_category(2)_B0D05C25C172D0737F04EF0AF0663D28, product_category(2)_BB4A179E615AD18488A859BC09B06D60, product_category(2)_A78952B21B4165ADA2189AE66887E2F1, product_category(2)_E789413C60FC1A6E1CA4DE376C188E1D, product_category(2)_49C166361658D9ACF79C78FC97272B01, product_category(2)_94AD28800A063F2E676E76DEA24E5FB9, product_category(2)_C1E60A42840668783CE8F9C783D33BD5, product_category(2)_939A40D09BD05A13C32B381245670495, product_category(2)_A064B48EA8588E500FE1523D1A696260, product_category(2)_346AC0DECB71FFDC9114236B419D7814, product_category(2)_7701F5CEE32DB638E1B6F59ED0CBD56D, product_category(2)_AFD1C37D8C150F6BD24EDB35AE6FAF29, product_category(2)_0F5AE38AFC0210BAE65C4C9491339B08, product_category(2)_FFBD847719C42D1F80F560739885435D, ...]
Index: []

[0 rows x 4229 columns]

In [213]:
def transform_df_into_df_with_one_hot_vectors(dataframe_to_transform):
    required_column_names_list = read_requred_column_names()
    
    import time
    import json
    
    data_as_dict = json.loads(dataframe_to_transform.T.to_json())
    transformed_data_as_dict = dict.fromkeys(required_column_names_list)

    samples = []

    for row_number in data_as_dict:
        transformed_row_as_dict = dict.fromkeys(required_column_names_list)
        transformed_row_as_dict['Sale'] = data_as_dict[str(row_number)]['Sale']
        transformed_row_as_dict['SalesAmountInEuro'] = data_as_dict[str(row_number)]['SalesAmountInEuro']
        transformed_row_as_dict['time_delay_for_conversion'] = data_as_dict[str(row_number)]['time_delay_for_conversion']
        transformed_row_as_dict['click_timestamp'] = data_as_dict[str(row_number)]['click_timestamp']
        transformed_row_as_dict['nb_clicks_1week'] = data_as_dict[str(row_number)]['nb_clicks_1week']
        for column_number, (column_name, cell_value) in enumerate(zip(data_as_dict[row_number].keys(), data_as_dict[row_number].values())):
            if column_number > 2:
                transformed_column_name = column_name + '_' + str(cell_value)
                if transformed_column_name in required_column_names_list:                
                    transformed_row_as_dict[transformed_column_name] = 1
        samples.append(transformed_row_as_dict)
    
    df = pd.DataFrame(samples)
    df = df.fillna(0)
    
    return df

In [214]:
import time
start = time.time()
d = transform_df_into_df_with_one_hot_vectors(df_original)
end = time.time()
print(end - start)
d[:5]

25.73498773574829

,Sale,SalesAmountInEuro,click_timestamp,device_type_-1,device_type_0C297EB7365042A7DCB803298164359F,device_type_1D2373C2A02F5A307C1F0C697ECF8429,device_type_7E56C27BFF0305E788DA55A029EC4988,device_type_B432A885981287B47E08B41E802860B2,device_type_C1ED32BB62670069B0ACE459169A7EAA,device_type_D5AF1EAB7526F8539A66F715079AB628,...,product_gender_4E0E101FFE4550D92B5CCDEF67A1FE17,product_gender_6EFABCEDA36A931DBF760F88970BAF0E,product_gender_86E2AFBF909EC95B069893FF0BBC5B26,product_gender_8CE4C5DDEE22BB8EE50CF418ED81591C,product_gender_A5D15FC386510762EC0DDFF54ABE6F94,product_gender_C45A9AC6D102ACAEEDF0D6F78636D84A,product_gender_C83584C67375245584CEBF5DCE5BEE2D,product_gender_D7B42B0C4D807EF1C13F79948743E9DA,product_gender_D894202FD3ABAE0B55F9FAE133412DE5,time_delay_for_conversion
0,0,-1.0,1596439471,0.0,0,0,0.0,0,0,0,...,0,0.0,0,0,1.0,0.0,0,0.0,0.0,-1
1,0,-1.0,1596439471,0.0,0,0,1.0,0,0,0,...,0,0.0,0,0,0.0,0.0,0,0.0,0.0,-1
2,1,21.24097,1596439471,0.0,0,0,0.0,0,0,0,...,0,0.0,0,0,0.0,0.0,0,0.0,0.0,965274
3,0,-1.0,1596439472,0.0,0,0,0.0,0,0,0,...,0,0.0,0,0,0.0,0.0,0,0.0,0.0,-1
4,0,-1.0,1596439472,0.0,0,0,0.0,0,0,0,...,0,0.0,0,0,1.0,0.0,0,0.0,0.0,-1

In [5]:
print(df_original.isnull().sum())
df = df_original.dropna(axis=0) # usuwanie wierszy, które zawierają null
df.isnull().sum()

Sale                         0
SalesAmountInEuro            0
time_delay_for_conversion    0
click_timestamp              0
nb_clicks_1week              0
product_price                0
product_age_group            0
device_type                  0
audience_id                  0
product_gender               0
product_brand                0
product_category(1)          0
product_category(2)          0
product_category(3)          0
product_category(4)          0
product_category(5)          0
product_category(6)          0
product_category(7)          0
product_country              0
product_id                   0
product_title                5
partner_id                   0
user_id                      0
dtype: int64

Sale                         0
SalesAmountInEuro            0
time_delay_for_conversion    0
click_timestamp              0
nb_clicks_1week              0
product_price                0
product_age_group            0
device_type                  0
audience_id                  0
product_gender               0
product_brand                0
product_category(1)          0
product_category(2)          0
product_category(3)          0
product_category(4)          0
product_category(5)          0
product_category(6)          0
product_category(7)          0
product_country              0
product_id                   0
product_title                0
partner_id                   0
user_id                      0
dtype: int64

In [4]:
columns = list(df)
for id, name in enumerate(columns):
    count = len(df.iloc[:,id].unique())
    print(str(id) + "\t" + str(count) +  "\t" + name  )

0	2	Sale
1	51695	SalesAmountInEuro
2	59290	time_delay_for_conversion
3	424739	click_timestamp
4	1824	nb_clicks_1week
5	13788	product_price
6	9	product_age_group
7	5	device_type
8	6345	audience_id
9	14	product_gender
10	11428	product_brand
11	22	product_category(1)
12	161	product_category(2)
13	877	product_category(3)
14	1227	product_category(4)
15	630	product_category(5)
16	142	product_category(6)
17	3	product_category(7)
18	17	product_country
19	232124	product_id
20	125389	product_title
21	199	partner_id
22	924093	user_id

In [5]:
# index_of_columns_with_lower_than_1000_unique_values = []
# excluded_indexes = [0, 1, 2, 3, 4, 5]
# for id, count in enumerate(count_of_unique_values_in_each_row):
#     if id not in excluded_indexes:
#         if count < 1000:
#             index_of_columns_with_lower_than_1000_unique_values.append(id)
# df = pd.get_dummies(df.iloc[:,index_of_columns_with_lower_than_1000_unique_values])

# df = pd.get_dummies(df.iloc[:,[6,7,9,11,12,13,14,15,16,17,18,21]])

import time
start = time.time()
df_copy=df
index_of_columns_to_change_to_one_hot_vectors = [6, 7, 9, 11, 12, 13, 14, 15, 16, 17, 18, 21]

df_only_one_hot_vectors_columns = pd.get_dummies(df_copy.iloc[:,index_of_columns_to_change_to_one_hot_vectors])
df_common_columns = df.iloc[:,[0, 1, 2, 4, 5 ]]


df_copy = pd.concat([df_common_columns, df_only_one_hot_vectors_columns ], axis=1, sort=True)

df_copy[:5]

end = time.time()
print(end - start)

TypeError: unsupported operand type(s) for -: 'float' and 'module'

In [7]:
start = time.time()
df_copy.to_csv("one_hot_vectors_data_1mln.csv", sep='\t', index=False)
end = time.time()
print(end - start)

TypeError: unsupported operand type(s) for -: 'float' and 'module'